[tool.mypy]
python_version = "3.12"
mypy_path = "stubs"
strict = true
packages = ["wadwise"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
ignore = ["E731", "E402"]

[tool.coverage.run]
source = ["wadwise"]

# [tool.coverage.report]
# fail_under = 100

# [[tool.mypy.overrides]]
# module = []
# ignore_missing_imports = true
