from typing import Any

def opt(*args: Any, **kwargs: Any) -> Any: ...
def item(*args: Any, **kwargs: Any) -> Any: ...
def enum(*args: Any) -> Any: ...
def Date(fmt: str) -> Any: ...
def Time(fmt: str) -> Any: ...
def DateTime(fmt: str) -> Any: ...
